import type {
  BusinessEntity,
  BusinessEntityDetail,
} from "@/features/records/business-entities/types";

export const MOCK_BUSINESS_ENTITIES: BusinessEntity[] = [
  {
    id: "ENT001",
    clientId: "1",
    clientName: "Keystone Health Partners",
    entityName: "Berks County Medical Associates, PC",
    location: "West Reading, PA",
    type: "Multi-Specialty Group",
    taxId: "23-1234567",
    groupNpis: ["1122334455"],
    providerCount: 156,
    activeContractsCount: 7,
    inProcessContractsCount: 0,
    endedContractsCount: 0,
    status: "active",
  },
  {
    id: "ENT002",
    clientId: "1",
    clientName: "Keystone Health Partners",
    entityName: "Reading Hospital Physician Services, PC",
    location: "West Reading, PA",
    type: "Hospital-Employed Group",
    taxId: "23-2345678",
    groupNpis: ["9876543210", "9876543211"],
    providerCount: 842,
    activeContractsCount: 12,
    inProcessContractsCount: 0,
    endedContractsCount: 0,
    status: "active",
  },
  {
    id: "ENT003",
    clientId: "1",
    clientName: "Keystone Health Partners",
    entityName: "Berks Valley Pediatrics, PLLC",
    location: "Reading, PA",
    type: "Pediatric Specialty",
    taxId: "23-3456789",
    groupNpis: ["1234567891"],
    providerCount: 24,
    activeContractsCount: 7,
    inProcessContractsCount: 0,
    endedContractsCount: 0,
    status: "active",
  },
  {
    id: "ENT004",
    clientId: "2",
    clientName: "Penn Medicine Network",
    entityName: "Penn Medicine Physicians Associates, LLC",
    location: "Philadelphia, PA",
    type: "Multi-Specialty Group",
    taxId: "23-4567890",
    groupNpis: ["2345678901", "2345678902"],
    providerCount: 1240,
    activeContractsCount: 8,
    inProcessContractsCount: 0,
    endedContractsCount: 0,
    status: "active",
  },
  {
    id: "ENT005",
    clientId: "4",
    clientName: "Lehigh Valley Medical Network",
    entityName: "Lehigh Valley Behavioral Health Associates, PA",
    location: "Scranton, PA",
    type: "Behavioral Health Group",
    taxId: "23-5678901",
    groupNpis: ["3456789012"],
    providerCount: 86,
    activeContractsCount: 5,
    inProcessContractsCount: 0,
    endedContractsCount: 0,
    status: "active",
  },
  {
    id: "ENT006",
    clientId: "3",
    clientName: "Three Rivers Health Network",
    entityName: "Three Rivers Physician Associates, PC",
    location: "Pittsburgh, PA",
    type: "Multi-Specialty Group",
    taxId: "25-1234567",
    groupNpis: ["4567890123", "4567890124", "4567890125", "4567890126"],
    providerCount: 1850,
    activeContractsCount: 9,
    inProcessContractsCount: 1,
    endedContractsCount: 0,
    status: "active",
  },
  {
    id: "ENT007",
    clientId: "3",
    clientName: "Three Rivers Health Network",
    entityName: "North Hills Medical Associates, LLC",
    location: "Pittsburgh, PA",
    type: "Primary Care Group",
    taxId: "25-2345678",
    groupNpis: ["5678901234", "5678901235"],
    providerCount: 78,
    activeContractsCount: 5,
    inProcessContractsCount: 0,
    endedContractsCount: 1,
    status: "active",
  },
  {
    id: "ENT008",
    clientId: "2",
    clientName: "Penn Medicine Network",
    entityName: "Penn Orthopedic Associates, PC",
    location: "Philadelphia, PA",
    type: "Single Specialty",
    taxId: "23-6789012",
    groupNpis: ["6789012345"],
    providerCount: 45,
    activeContractsCount: 6,
    inProcessContractsCount: 0,
    endedContractsCount: 0,
    status: "active",
  },
  {
    id: "ENT009",
    clientId: "5",
    clientName: "Eagles Urgent Care Network",
    entityName: "Eagles Urgent Care Center, LLC",
    location: "Philadelphia, PA",
    type: "Urgent Care",
    taxId: "15-7894561",
    groupNpis: ["7890123456"],
    providerCount: 14,
    activeContractsCount: 3,
    inProcessContractsCount: 0,
    endedContractsCount: 0,
    status: "active",
  },
  {
    id: "ENT010",
    clientId: "4",
    clientName: "Lehigh Valley Medical Network",
    entityName: "Valley Diagnostics Center, LLC",
    location: "Scranton, PA",
    type: "Imaging Center",
    taxId: "14-8901234",
    groupNpis: ["8901234567"],
    providerCount: 12,
    activeContractsCount: 4,
    inProcessContractsCount: 0,
    endedContractsCount: 0,
    status: "active",
  },
];

export const BUSINESS_ENTITY_TYPES = [
  "Multi-Specialty Group",
  "Primary Care Group",
  "Single Specialty",
  "Hospital-Employed Group",
  "IPA",
  "Pediatric Specialty",
  "Behavioral Health Group",
  "ASC",
  "Lab",
  "Imaging Center",
  "Urgent Care",
  "Dialysis Center",
  "Home Health",
] as const;

export function getBusinessEntityById(id: string): BusinessEntity | undefined {
  return MOCK_BUSINESS_ENTITIES.find((entity) => entity.id === id);
}

/** Extended detail mock for ENT001 (matches shared HTML). Other IDs get base entity. */
const ENTITY_DETAIL_OVERRIDES: Record<string, Partial<BusinessEntityDetail>> = {
  ENT001: {
    groupNpis: ["1122334455"],
    primaryNpi2: "1122334455",
    entityType: "Physician Group",
    subtype: "Multi-Specialty Group",
    locationCount: 2,
    contactPerson: {
      name: "Maria Rodriguez",
      title: "Practice Administrator",
      phone: "(610) 988-8002",
      email: "mrodriguez@keystonemedical.org",
    },
    authorizedOfficial: {
      name: "Dr. Robert Chen",
      title: "Medical Director",
      npi1: "1234509876",
      email: "rchen@keystonemedical.org",
      ssn: "Not set",
      dateOfBirth: "Not set",
    },
    phone: "(610) 988-8000",
    fax: "(610) 988-8001",
    email: "admin@keystonemedical.org",
    website: "www.keystonemedical.org",
    groupNpiDetails: [
      {
        npi: "1122334455",
        label: "Berks County Medical Associates",
        isPrimary: true,
        locations: [
          {
            id: "LOC001",
            type: "primary",
            address: "100 Medical Campus Dr",
            cityStateZip: "West Reading, PA 19611",
            phone: "(610) 988-8000",
          },
          {
            id: "LOC002",
            type: "service",
            address: "250 Penn Ave, Suite 100",
            cityStateZip: "West Reading, PA 19611",
            phone: "(610) 988-8050",
          },
        ],
      },
    ],
    locations: [
      {
        id: "LOC001",
        type: "service",
        isPrimary: true,
        isAdaAccessible: true,
        npiRef: "1122334455",
        npiLabel: "Berks County Medical Associates",
        address: "100 Medical Campus Dr",
        cityStateZip: "West Reading, PA 19611",
        phone: "(610) 988-8000",
        manager: "Maria Rodriguez",
        hoursOfOperation: [
          { day: "Mon", hours: "9:00-5:00" },
          { day: "Tue", hours: "9:00-5:00" },
          { day: "Wed", hours: "9:00-5:00" },
          { day: "Thu", hours: "9:00-5:00" },
          { day: "Fri", hours: "9:00-5:00" },
        ],
        payerLocationIds: [
          { payerName: "Aetna", locationId: "AET-8800" },
          { payerName: "BCBS", locationId: "BCBS-4400" },
          { payerName: "UHC", locationId: "UHC-2200" },
        ],
      },
      {
        id: "LOC002",
        type: "service",
        isPrimary: false,
        isAdaAccessible: true,
        npiRef: "1122334455",
        npiLabel: "Berks County Medical Associates",
        address: "250 Penn Ave, Suite 100",
        cityStateZip: "West Reading, PA 19611",
        phone: "(610) 988-8050",
        manager: "Thomas Wright",
        hoursOfOperation: [
          { day: "Mon", hours: "9:00-5:00" },
          { day: "Tue", hours: "9:00-5:00" },
          { day: "Wed", hours: "9:00-5:00" },
          { day: "Thu", hours: "9:00-5:00" },
          { day: "Fri", hours: "9:00-5:00" },
        ],
        payerLocationIds: [
          { payerName: "UHC", locationId: "UHC-2201" },
        ],
      },
      {
        id: "LOC003",
        type: "billing",
        isPrimary: true,
        isPrivate: true,
        address: "PO Box 16052",
        cityStateZip: "Reading, PA 19612",
        phone: "(610) 988-8100",
      },
      {
        id: "LOC004",
        type: "mailing",
        isPrimary: true,
        address: "100 Medical Campus Dr",
        cityStateZip: "West Reading, PA 19611",
        phone: "(610) 988-8000",
      },
    ],
    affiliatedProviders: [
      {
        id: "PRV001",
        firstName: "Jennifer",
        lastName: "Chen",
        credential: "MD",
        specialty: "Internal Medicine",
        npi1: "1234567890",
        employmentStatus: "active",
        licenseExpiryDays: 185,
      },
      {
        id: "PRV002",
        firstName: "Michael",
        lastName: "Thompson",
        credential: "DO",
        specialty: "Family Medicine",
        npi1: "2345678901",
        employmentStatus: "active",
        licenseExpiryDays: 42,
      },
      {
        id: "PRV003",
        firstName: "Sarah",
        lastName: "Williams",
        credential: "MD",
        specialty: "Cardiology",
        npi1: "3456789012",
        employmentStatus: "on_leave",
        licenseExpiryDays: 260,
      },
      {
        id: "PRV004",
        firstName: "Emily",
        lastName: "Rodriguez",
        credential: "MD",
        specialty: "Pediatrics",
        npi1: "5555555555",
        employmentStatus: "active",
        licenseExpiryDays: 320,
      },
      {
        id: "PRV005",
        firstName: "David",
        lastName: "Park",
        credential: "MD",
        specialty: "Orthopedics",
        npi1: "6666666666",
        employmentStatus: "active",
        licenseExpiryDays: 15,
      },
      {
        id: "PRV006",
        firstName: "Lisa",
        lastName: "Nguyen",
        credential: "NP",
        specialty: "Dermatology",
        npi1: "7777777777",
        employmentStatus: "inactive",
        licenseExpiryDays: 0,
      },
    ],
    payerContracts: [
      {
        id: "CTR001",
        payerName: "Medicare (Novitas)",
        category: "government",
        effectiveDate: "2015-01-01",
        renewalDate: "2025-01-01",
        delegation: "non-delegated",
        status: "active",
      },
      {
        id: "CTR002",
        payerName: "PA Medical Assistance (FFS)",
        category: "government",
        effectiveDate: "2018-07-01",
        renewalDate: "2025-07-01",
        delegation: "non-delegated",
        status: "active",
      },
      {
        id: "CTR003",
        payerName: "AmeriHealth Caritas PA",
        category: "government",
        effectiveDate: "2020-01-01",
        renewalDate: "2026-01-01",
        delegation: "non-delegated",
        status: "active",
      },
      {
        id: "CTR004",
        payerName: "Highmark BCBS PA",
        category: "commercial",
        effectiveDate: "2016-01-01",
        renewalDate: "2026-01-01",
        delegation: "delegated",
        status: "active",
      },
      {
        id: "CTR005",
        payerName: "UPMC Health Plan",
        category: "commercial",
        effectiveDate: "2019-03-01",
        renewalDate: "2025-03-01",
        delegation: "delegated",
        status: "active",
      },
      {
        id: "CTR006",
        payerName: "Aetna",
        category: "commercial",
        effectiveDate: "2017-06-15",
        renewalDate: "2025-06-15",
        delegation: "non-delegated",
        status: "active",
      },
      {
        id: "CTR007",
        payerName: "UPMC for Life (MA)",
        category: "government",
        effectiveDate: "2019-01-01",
        renewalDate: "2025-01-01",
        delegation: "delegated",
        status: "active",
      },
    ],
  },
};

export function getBusinessEntityDetailById(
  id: string
): BusinessEntityDetail | undefined {
  const base = getBusinessEntityById(id);
  if (!base) return undefined;
  const overrides = ENTITY_DETAIL_OVERRIDES[id];
  return {
    ...base,
    ...overrides,
    entityType: overrides?.entityType ?? base.type,
    subtype: overrides?.subtype ?? base.type,
    locationCount: overrides?.locationCount ?? 0,
  };
}

export function getUniqueClients() {
  const clientMap = new Map<string, { id: string; name: string }>();
  
  for (const entity of MOCK_BUSINESS_ENTITIES) {
    if (!clientMap.has(entity.clientId)) {
      clientMap.set(entity.clientId, {
        id: entity.clientId,
        name: entity.clientName,
      });
    }
  }
  
  return Array.from(clientMap.values()).sort((a, b) => 
    a.name.localeCompare(b.name)
  );
}
