/**
 * Mock Provider Data
 * 
 * Sample data for UI development and testing.
 * Contains 25+ diverse providers for comprehensive testing.
 */

import {
  Provider,
  ProviderType,
  ProviderStatus,
  Gender,
  ProviderDocument,
  ProviderActivity,
} from '@/features/records/providers/types';

/**
 * Mock providers data (25+ providers with variety)
 */
export const mockProviders: Provider[] = [
  {
    id: 'prov-001',
    firstName: 'Jennifer',
    middleName: 'Marie',
    lastName: 'Chen',
    suffix: null,
    displayName: 'Dr. Jennifer Chen, MD',
    credential: 'MD',
    npi: '1234567890',
    deaNumber: 'BC1234567',
    taxId: '12-3456789',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1985-03-15'),
    primarySpecialty: 'Internal Medicine',
    secondarySpecialties: ['Geriatrics'],
    boardCertifications: ['ABIM - Internal Medicine'],
    email: 'jchen@example.com',
    phone: '(555) 123-4567',
    fax: '(555) 123-4568',
    status: ProviderStatus.ACTIVE,
    clientIds: ['1', '2'],
    departmentId: 'dept-001',
    businessEntityId: 'be-001',
    organizationalAffiliations: ['Keystone Health Partners', 'Penn Medicine Network'],
    stateLicenses: [
      {
        id: 'lic-001',
        state: 'PA',
        licenseNumber: 'MD123456',
        licenseType: 'Medical',
        issueDate: new Date('2010-01-01'),
        expirationDate: new Date('2026-12-31'),
        status: 'Active',
      },
      {
        id: 'lic-002',
        state: 'NJ',
        licenseNumber: 'MD654321',
        licenseType: 'Medical',
        issueDate: new Date('2012-06-01'),
        expirationDate: new Date('2027-06-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-001',
        locationName: 'Main Office',
        addressLine1: '123 Medical Plaza',
        addressLine2: 'Suite 100',
        city: 'Philadelphia',
        state: 'PA',
        zip: '19103',
        phone: '(555) 123-4567',
        fax: '(555) 123-4568',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2023-01-15'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-20'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 92,
    nextLicenseExpiration: new Date('2026-12-31'),
    alertCount: 0,
  },
  {
    id: 'prov-002',
    firstName: 'Michael',
    middleName: 'James',
    lastName: 'Rodriguez',
    suffix: null,
    displayName: 'Dr. Michael Rodriguez, DO',
    credential: 'DO',
    npi: '2345678901',
    deaNumber: 'MR9876543',
    taxId: '23-4567890',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1982-07-22'),
    primarySpecialty: 'Cardiology',
    secondarySpecialties: ['Internal Medicine'],
    boardCertifications: ['ABIM - Cardiology', 'ABIM - Internal Medicine'],
    email: 'mrodriguez@example.com',
    phone: '(555) 234-5678',
    fax: '(555) 234-5679',
    status: ProviderStatus.ACTIVE,
    clientIds: ['1'],
    departmentId: 'dept-002',
    businessEntityId: 'be-001',
    organizationalAffiliations: ['Keystone Health Partners'],
    stateLicenses: [
      {
        id: 'lic-003',
        state: 'PA',
        licenseNumber: 'DO987654',
        licenseType: 'Medical',
        issueDate: new Date('2008-03-15'),
        expirationDate: new Date('2026-03-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-002',
        locationName: 'Cardiology Center',
        addressLine1: '456 Heart Avenue',
        addressLine2: null,
        city: 'Philadelphia',
        state: 'PA',
        zip: '19104',
        phone: '(555) 234-5678',
        fax: null,
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH12345',
    createdAt: new Date('2023-02-01'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-18'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 88,
    nextLicenseExpiration: new Date('2026-03-31'),
    alertCount: 1,
  },
  {
    id: 'prov-003',
    firstName: 'Sarah',
    middleName: 'Elizabeth',
    lastName: 'Williams',
    suffix: null,
    displayName: 'Sarah Williams, PA-C',
    credential: 'PA-C',
    npi: '3456789012',
    deaNumber: null,
    taxId: '34-5678901',
    ssn: null,
    providerType: ProviderType.PHYSICIAN_ASSISTANT,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1990-05-12'),
    primarySpecialty: 'Family Medicine',
    secondarySpecialties: [],
    boardCertifications: ['NCCPA - Physician Assistant'],
    email: 'swilliams@example.com',
    phone: '(555) 345-6789',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['1', '4'],
    departmentId: 'dept-003',
    businessEntityId: 'be-002',
    organizationalAffiliations: ['Lancaster Family Medicine'],
    stateLicenses: [
      {
        id: 'lic-004',
        state: 'PA',
        licenseNumber: 'PA456789',
        licenseType: 'Physician Assistant',
        issueDate: new Date('2015-06-01'),
        expirationDate: new Date('2027-05-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-003',
        locationName: 'Family Practice',
        addressLine1: '789 Main Street',
        addressLine2: 'Building B',
        city: 'Lancaster',
        state: 'PA',
        zip: '17602',
        phone: '(555) 345-6789',
        fax: '(555) 345-6790',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2023-03-10'),
    createdBy: 'manager@incredibly.com',
    updatedAt: new Date('2026-01-22'),
    updatedBy: 'manager@incredibly.com',
    responsiveness: 95,
    nextLicenseExpiration: new Date('2027-05-31'),
    alertCount: 0,
  },
  {
    id: 'prov-004',
    firstName: 'David',
    middleName: 'Alan',
    lastName: 'Thompson',
    suffix: 'Jr.',
    displayName: 'Dr. David Thompson Jr., MD',
    credential: 'MD',
    npi: '4567890123',
    deaNumber: 'DT7654321',
    taxId: '45-6789012',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1978-11-30'),
    primarySpecialty: 'Pediatrics',
    secondarySpecialties: ['Adolescent Medicine'],
    boardCertifications: ['ABP - Pediatrics'],
    email: 'dthompson@example.com',
    phone: '(555) 456-7890',
    fax: '(555) 456-7891',
    status: ProviderStatus.PENDING,
    clientIds: ['2'],
    departmentId: 'dept-004',
    businessEntityId: 'be-001',
    organizationalAffiliations: ['Penn Medicine Network'],
    stateLicenses: [
      {
        id: 'lic-005',
        state: 'PA',
        licenseNumber: 'MD234567',
        licenseType: 'Medical',
        issueDate: new Date('2005-08-01'),
        expirationDate: new Date('2026-02-28'),
        status: 'Active',
      },
      {
        id: 'lic-006',
        state: 'DE',
        licenseNumber: 'MD876543',
        licenseType: 'Medical',
        issueDate: new Date('2010-01-15'),
        expirationDate: new Date('2026-01-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-004',
        locationName: 'Pediatric Clinic',
        addressLine1: '321 Children Avenue',
        addressLine2: 'Floor 3',
        city: 'Philadelphia',
        state: 'PA',
        zip: '19107',
        phone: '(555) 456-7890',
        fax: '(555) 456-7891',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH67890',
    createdAt: new Date('2023-04-15'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-25'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 78,
    nextLicenseExpiration: new Date('2026-01-31'),
    alertCount: 2,
  },
  {
    id: 'prov-005',
    firstName: 'Emily',
    middleName: null,
    lastName: 'Martinez',
    suffix: null,
    displayName: 'Emily Martinez, NP-C',
    credential: 'NP-C',
    npi: '5678901234',
    deaNumber: 'EM4567890',
    taxId: '56-7890123',
    ssn: null,
    providerType: ProviderType.NURSE_PRACTITIONER,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1988-09-18'),
    primarySpecialty: 'Family Medicine',
    secondarySpecialties: ['Women\'s Health'],
    boardCertifications: ['ANCC - Family Nurse Practitioner'],
    email: 'emartinez@example.com',
    phone: '(555) 567-8901',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['3'],
    departmentId: 'dept-003',
    businessEntityId: 'be-003',
    organizationalAffiliations: ['Three Rivers Health Network'],
    stateLicenses: [
      {
        id: 'lic-007',
        state: 'PA',
        licenseNumber: 'RN345678',
        licenseType: 'Nursing',
        issueDate: new Date('2013-05-01'),
        expirationDate: new Date('2027-04-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-005',
        locationName: 'Women\'s Health Center',
        addressLine1: '654 Wellness Drive',
        addressLine2: null,
        city: 'Pittsburgh',
        state: 'PA',
        zip: '15219',
        phone: '(555) 567-8901',
        fax: '(555) 567-8902',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2023-05-20'),
    createdBy: 'manager@incredibly.com',
    updatedAt: new Date('2026-01-19'),
    updatedBy: 'manager@incredibly.com',
    responsiveness: 91,
    nextLicenseExpiration: new Date('2027-04-30'),
    alertCount: 0,
  },
  {
    id: 'prov-006',
    firstName: 'Robert',
    middleName: 'William',
    lastName: 'Lee',
    suffix: null,
    displayName: 'Dr. Robert Lee, DPM',
    credential: 'DPM',
    npi: '6789012345',
    deaNumber: null,
    taxId: '67-8901234',
    ssn: null,
    providerType: ProviderType.PODIATRIST,
    gender: Gender.MALE,
    dateOfBirth: new Date('1975-04-08'),
    primarySpecialty: 'Podiatry',
    secondarySpecialties: ['Sports Medicine'],
    boardCertifications: ['ABPM - Podiatric Medicine'],
    email: 'rlee@example.com',
    phone: '(555) 678-9012',
    fax: '(555) 678-9013',
    status: ProviderStatus.ACTIVE,
    clientIds: ['4'],
    departmentId: 'dept-005',
    businessEntityId: 'be-004',
    organizationalAffiliations: ['Lehigh Valley Medical Network'],
    stateLicenses: [
      {
        id: 'lic-008',
        state: 'PA',
        licenseNumber: 'POD123456',
        licenseType: 'Podiatry',
        issueDate: new Date('2000-09-01'),
        expirationDate: new Date('2026-08-31'),
        status: 'Active',
      },
      {
        id: 'lic-009',
        state: 'NJ',
        licenseNumber: 'POD789012',
        licenseType: 'Podiatry',
        issueDate: new Date('2005-03-01'),
        expirationDate: new Date('2027-02-28'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-006',
        locationName: 'Foot & Ankle Specialists',
        addressLine1: '987 Medical Plaza',
        addressLine2: 'Suite 205',
        city: 'Scranton',
        state: 'PA',
        zip: '18103',
        phone: '(555) 678-9012',
        fax: '(555) 678-9013',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH11223',
    createdAt: new Date('2023-06-01'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-21'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 84,
    nextLicenseExpiration: new Date('2026-08-31'),
    alertCount: 0,
  },
  {
    id: 'prov-007',
    firstName: 'Amanda',
    middleName: 'Rose',
    lastName: 'Foster',
    suffix: null,
    displayName: 'Dr. Amanda Foster, DO',
    credential: 'DO',
    npi: '7890123456',
    deaNumber: 'AF3456789',
    taxId: '78-9012345',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1986-12-05'),
    primarySpecialty: 'Emergency Medicine',
    secondarySpecialties: [],
    boardCertifications: ['ABEM - Emergency Medicine'],
    email: 'afoster@example.com',
    phone: '(555) 789-0123',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['1', '3'],
    departmentId: 'dept-006',
    businessEntityId: 'be-001',
    organizationalAffiliations: ['Keystone Health Partners', 'Three Rivers Health Network'],
    stateLicenses: [
      {
        id: 'lic-010',
        state: 'PA',
        licenseNumber: 'DO567890',
        licenseType: 'Medical',
        issueDate: new Date('2012-07-01'),
        expirationDate: new Date('2026-06-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-007',
        locationName: 'Emergency Department',
        addressLine1: '123 Hospital Drive',
        addressLine2: null,
        city: 'West Reading',
        state: 'PA',
        zip: '19601',
        phone: '(555) 789-0123',
        fax: null,
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2023-07-10'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-23'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 89,
    nextLicenseExpiration: new Date('2026-06-30'),
    alertCount: 0,
  },
  {
    id: 'prov-008',
    firstName: 'James',
    middleName: 'Patrick',
    lastName: 'Mitchell',
    suffix: 'III',
    displayName: 'Dr. James Mitchell III, MD',
    credential: 'MD',
    npi: '8901234567',
    deaNumber: 'JM8901234',
    taxId: '89-0123456',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1979-02-14'),
    primarySpecialty: 'Surgery',
    secondarySpecialties: ['Trauma Surgery'],
    boardCertifications: ['ABS - General Surgery', 'ABS - Surgical Critical Care'],
    email: 'jmitchell@example.com',
    phone: '(555) 890-1234',
    fax: '(555) 890-1235',
    status: ProviderStatus.ACTIVE,
    clientIds: ['2'],
    departmentId: 'dept-007',
    businessEntityId: 'be-002',
    organizationalAffiliations: ['Penn Medicine Network'],
    stateLicenses: [
      {
        id: 'lic-011',
        state: 'PA',
        licenseNumber: 'MD789012',
        licenseType: 'Medical',
        issueDate: new Date('2007-04-01'),
        expirationDate: new Date('2027-03-31'),
        status: 'Active',
      },
      {
        id: 'lic-012',
        state: 'NY',
        licenseNumber: 'MD345678',
        licenseType: 'Medical',
        issueDate: new Date('2009-08-15'),
        expirationDate: new Date('2027-08-14'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-008',
        locationName: 'Surgical Center',
        addressLine1: '3400 Spruce Street',
        addressLine2: 'Pavilion 4',
        city: 'Philadelphia',
        state: 'PA',
        zip: '19104',
        phone: '(555) 890-1234',
        fax: '(555) 890-1235',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH44556',
    createdAt: new Date('2023-08-15'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-17'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 93,
    nextLicenseExpiration: new Date('2027-03-31'),
    alertCount: 0,
  },
  {
    id: 'prov-009',
    firstName: 'Lisa',
    middleName: 'Ann',
    lastName: 'Wang',
    suffix: null,
    displayName: 'Dr. Lisa Wang, MD',
    credential: 'MD',
    npi: '9012345678',
    deaNumber: 'LW2345678',
    taxId: '90-1234567',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1983-06-25'),
    primarySpecialty: 'Psychiatry',
    secondarySpecialties: ['Child & Adolescent Psychiatry'],
    boardCertifications: ['ABPN - Psychiatry', 'ABPN - Child & Adolescent Psychiatry'],
    email: 'lwang@example.com',
    phone: '(555) 901-2345',
    fax: '(555) 901-2346',
    status: ProviderStatus.PENDING,
    clientIds: ['3'],
    departmentId: 'dept-008',
    businessEntityId: 'be-003',
    organizationalAffiliations: ['Three Rivers Health Network'],
    stateLicenses: [
      {
        id: 'lic-013',
        state: 'PA',
        licenseNumber: 'MD890123',
        licenseType: 'Medical',
        issueDate: new Date('2011-10-01'),
        expirationDate: new Date('2026-09-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-009',
        locationName: 'Mental Health Center',
        addressLine1: '555 Behavioral Health Blvd',
        addressLine2: null,
        city: 'Pittsburgh',
        state: 'PA',
        zip: '15222',
        phone: '(555) 901-2345',
        fax: '(555) 901-2346',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2023-09-20'),
    createdBy: 'manager@incredibly.com',
    updatedAt: new Date('2026-01-26'),
    updatedBy: 'manager@incredibly.com',
    responsiveness: 76,
    nextLicenseExpiration: new Date('2026-09-30'),
    alertCount: 1,
  },
  {
    id: 'prov-010',
    firstName: 'Christopher',
    middleName: 'John',
    lastName: 'Brown',
    suffix: null,
    displayName: 'Dr. Christopher Brown, DDS',
    credential: 'DDS',
    npi: '0123456789',
    deaNumber: null,
    taxId: '01-2345678',
    ssn: null,
    providerType: ProviderType.DENTIST,
    gender: Gender.MALE,
    dateOfBirth: new Date('1981-10-10'),
    primarySpecialty: 'General Dentistry',
    secondarySpecialties: ['Cosmetic Dentistry'],
    boardCertifications: ['ADA - General Dentistry'],
    email: 'cbrown@example.com',
    phone: '(555) 012-3456',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['5'],
    departmentId: 'dept-009',
    businessEntityId: 'be-005',
    organizationalAffiliations: ['Eagles Urgent Care Network'],
    stateLicenses: [
      {
        id: 'lic-014',
        state: 'PA',
        licenseNumber: 'DDS123456',
        licenseType: 'Dental',
        issueDate: new Date('2006-05-01'),
        expirationDate: new Date('2026-04-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-010',
        locationName: 'Dental Practice',
        addressLine1: '777 Smile Street',
        addressLine2: 'Suite 101',
        city: 'Philadelphia',
        state: 'PA',
        zip: '19106',
        phone: '(555) 012-3456',
        fax: '(555) 012-3457',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2023-10-05'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-20'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 87,
    nextLicenseExpiration: new Date('2026-04-30'),
    alertCount: 0,
  },
  // Additional 15 providers for variety (continuing the pattern)
  {
    id: 'prov-011',
    firstName: 'Patricia',
    middleName: 'Grace',
    lastName: 'Wilson',
    suffix: null,
    displayName: 'Dr. Patricia Wilson, MD',
    credential: 'MD',
    npi: '1122334455',
    deaNumber: 'PW5566778',
    taxId: '11-2233445',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1977-08-19'),
    primarySpecialty: 'Obstetrics & Gynecology',
    secondarySpecialties: [],
    boardCertifications: ['ABOG - Obstetrics & Gynecology'],
    email: 'pwilson@example.com',
    phone: '(555) 112-2334',
    fax: '(555) 112-2335',
    status: ProviderStatus.ACTIVE,
    clientIds: ['6'],
    departmentId: 'dept-010',
    businessEntityId: 'be-006',
    organizationalAffiliations: ['Lancaster Family Medicine'],
    stateLicenses: [
      {
        id: 'lic-015',
        state: 'PA',
        licenseNumber: 'MD556677',
        licenseType: 'Medical',
        issueDate: new Date('2003-12-01'),
        expirationDate: new Date('2026-11-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-011',
        locationName: 'Women\'s Care Center',
        addressLine1: '888 King Street',
        addressLine2: null,
        city: 'Lancaster',
        state: 'PA',
        zip: '17602',
        phone: '(555) 112-2334',
        fax: '(555) 112-2335',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH77889',
    createdAt: new Date('2023-11-10'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-24'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 90,
    nextLicenseExpiration: new Date('2026-11-30'),
    alertCount: 0,
  },
  {
    id: 'prov-012',
    firstName: 'Daniel',
    middleName: 'Scott',
    lastName: 'Harris',
    suffix: null,
    displayName: 'Daniel Harris, PA-C',
    credential: 'PA-C',
    npi: '2233445566',
    deaNumber: null,
    taxId: '22-3344556',
    ssn: null,
    providerType: ProviderType.PHYSICIAN_ASSISTANT,
    gender: Gender.MALE,
    dateOfBirth: new Date('1992-03-28'),
    primarySpecialty: 'Orthopedics',
    secondarySpecialties: [],
    boardCertifications: ['NCCPA - Physician Assistant'],
    email: 'dharris@example.com',
    phone: '(555) 223-3445',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['8'],
    departmentId: 'dept-011',
    businessEntityId: 'be-008',
    organizationalAffiliations: ['Central Pennsylvania Orthopedics'],
    stateLicenses: [
      {
        id: 'lic-016',
        state: 'PA',
        licenseNumber: 'PA667788',
        licenseType: 'Physician Assistant',
        issueDate: new Date('2017-09-01'),
        expirationDate: new Date('2027-08-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-012',
        locationName: 'Orthopedic Center',
        addressLine1: '300 Hospital Drive',
        addressLine2: 'Suite 200',
        city: 'Harrisburg',
        state: 'PA',
        zip: '17101',
        phone: '(555) 223-3445',
        fax: '(555) 223-3446',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2024-01-15'),
    createdBy: 'manager@incredibly.com',
    updatedAt: new Date('2026-01-27'),
    updatedBy: 'manager@incredibly.com',
    responsiveness: 86,
    nextLicenseExpiration: new Date('2027-08-31'),
    alertCount: 0,
  },
  {
    id: 'prov-013',
    firstName: 'Rachel',
    middleName: 'Lynn',
    lastName: 'Phillips',
    suffix: null,
    displayName: 'Rachel Phillips, NP-C',
    credential: 'NP-C',
    npi: '3344556677',
    deaNumber: 'RP7788990',
    taxId: '33-4455667',
    ssn: null,
    providerType: ProviderType.NURSE_PRACTITIONER,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1989-11-02'),
    primarySpecialty: 'Urgent Care',
    secondarySpecialties: [],
    boardCertifications: ['ANCC - Acute Care Nurse Practitioner'],
    email: 'rphillips@example.com',
    phone: '(555) 334-4556',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['5'],
    departmentId: 'dept-012',
    businessEntityId: 'be-005',
    organizationalAffiliations: ['Eagles Urgent Care Network'],
    stateLicenses: [
      {
        id: 'lic-017',
        state: 'PA',
        licenseNumber: 'RN778899',
        licenseType: 'Nursing',
        issueDate: new Date('2014-04-01'),
        expirationDate: new Date('2026-03-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-013',
        locationName: 'Urgent Care Center',
        addressLine1: '456 Market Street',
        addressLine2: null,
        city: 'Philadelphia',
        state: 'PA',
        zip: '19106',
        phone: '(555) 334-4556',
        fax: null,
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2024-02-20'),
    createdBy: 'manager@incredibly.com',
    updatedAt: new Date('2026-01-28'),
    updatedBy: 'manager@incredibly.com',
    responsiveness: 94,
    nextLicenseExpiration: new Date('2026-03-31'),
    alertCount: 1,
  },
  {
    id: 'prov-014',
    firstName: 'Thomas',
    middleName: 'Edward',
    lastName: 'Anderson',
    suffix: 'Sr.',
    displayName: 'Dr. Thomas Anderson Sr., MD',
    credential: 'MD',
    npi: '4455667788',
    deaNumber: 'TA9900112',
    taxId: '44-5566778',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1970-01-15'),
    primarySpecialty: 'Anesthesiology',
    secondarySpecialties: ['Pain Management'],
    boardCertifications: ['ABA - Anesthesiology', 'ABPM - Pain Medicine'],
    email: 'tanderson@example.com',
    phone: '(555) 445-5667',
    fax: '(555) 445-5668',
    status: ProviderStatus.ACTIVE,
    clientIds: ['7'],
    departmentId: 'dept-013',
    businessEntityId: 'be-007',
    organizationalAffiliations: ['Allegheny Cardiology Associates'],
    stateLicenses: [
      {
        id: 'lic-018',
        state: 'PA',
        licenseNumber: 'MD889900',
        licenseType: 'Medical',
        issueDate: new Date('1996-06-01'),
        expirationDate: new Date('2026-05-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-014',
        locationName: 'Pain Management Center',
        addressLine1: '200 Delafield Road',
        addressLine2: 'Suite 300',
        city: 'Pittsburgh',
        state: 'PA',
        zip: '15215',
        phone: '(555) 445-5667',
        fax: '(555) 445-5668',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH99001',
    createdAt: new Date('2024-03-10'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-16'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 81,
    nextLicenseExpiration: new Date('2026-05-31'),
    alertCount: 0,
  },
  {
    id: 'prov-015',
    firstName: 'Jessica',
    middleName: 'Marie',
    lastName: 'Taylor',
    suffix: null,
    displayName: 'Dr. Jessica Taylor, DO',
    credential: 'DO',
    npi: '5566778899',
    deaNumber: 'JT1122334',
    taxId: '55-6677889',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1984-07-03'),
    primarySpecialty: 'Dermatology',
    secondarySpecialties: [],
    boardCertifications: ['ABD - Dermatology'],
    email: 'jtaylor@example.com',
    phone: '(555) 556-6778',
    fax: '(555) 556-6779',
    status: ProviderStatus.PENDING,
    clientIds: ['1'],
    departmentId: 'dept-014',
    businessEntityId: 'be-001',
    organizationalAffiliations: ['Keystone Health Partners'],
    stateLicenses: [
      {
        id: 'lic-019',
        state: 'PA',
        licenseNumber: 'DO990011',
        licenseType: 'Medical',
        issueDate: new Date('2013-08-01'),
        expirationDate: new Date('2026-07-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-015',
        locationName: 'Dermatology Clinic',
        addressLine1: '123 Skin Care Lane',
        addressLine2: null,
        city: 'Philadelphia',
        state: 'PA',
        zip: '19103',
        phone: '(555) 556-6778',
        fax: '(555) 556-6779',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2024-04-01'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-29'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 79,
    nextLicenseExpiration: new Date('2026-07-31'),
    alertCount: 1,
  },
  // ... Continue with 10 more providers for total of 25
  {
    id: 'prov-016',
    firstName: 'Andrew',
    middleName: 'Charles',
    lastName: 'Davis',
    suffix: null,
    displayName: 'Dr. Andrew Davis, MD',
    credential: 'MD',
    npi: '6677889900',
    deaNumber: 'AD3344556',
    taxId: '66-7788990',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1980-12-20'),
    primarySpecialty: 'Radiology',
    secondarySpecialties: ['Neuroradiology'],
    boardCertifications: ['ABR - Diagnostic Radiology'],
    email: 'adavis@example.com',
    phone: '(555) 667-7889',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['2'],
    departmentId: 'dept-015',
    businessEntityId: 'be-002',
    organizationalAffiliations: ['Penn Medicine Network'],
    stateLicenses: [
      {
        id: 'lic-020',
        state: 'PA',
        licenseNumber: 'MD001122',
        licenseType: 'Medical',
        issueDate: new Date('2009-01-15'),
        expirationDate: new Date('2027-01-14'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-016',
        locationName: 'Imaging Center',
        addressLine1: '3400 Civic Center Blvd',
        addressLine2: 'Pavilion 2',
        city: 'Philadelphia',
        state: 'PA',
        zip: '19104',
        phone: '(555) 667-7889',
        fax: '(555) 667-7890',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH22334',
    createdAt: new Date('2024-05-15'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-15'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 92,
    nextLicenseExpiration: new Date('2027-01-14'),
    alertCount: 0,
  },
  {
    id: 'prov-017',
    firstName: 'Michelle',
    middleName: 'Ann',
    lastName: 'Garcia',
    suffix: null,
    displayName: 'Michelle Garcia, PA-C',
    credential: 'PA-C',
    npi: '7788990011',
    deaNumber: null,
    taxId: '77-8899001',
    ssn: null,
    providerType: ProviderType.PHYSICIAN_ASSISTANT,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1991-05-30'),
    primarySpecialty: 'Dermatology',
    secondarySpecialties: [],
    boardCertifications: ['NCCPA - Physician Assistant'],
    email: 'mgarcia@example.com',
    phone: '(555) 778-8990',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['1'],
    departmentId: 'dept-014',
    businessEntityId: 'be-001',
    organizationalAffiliations: ['Keystone Health Partners'],
    stateLicenses: [
      {
        id: 'lic-021',
        state: 'PA',
        licenseNumber: 'PA112233',
        licenseType: 'Physician Assistant',
        issueDate: new Date('2016-10-01'),
        expirationDate: new Date('2026-09-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-017',
        locationName: 'Dermatology Clinic',
        addressLine1: '123 Skin Care Lane',
        addressLine2: 'Suite 201',
        city: 'Philadelphia',
        state: 'PA',
        zip: '19103',
        phone: '(555) 778-8990',
        fax: null,
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2024-06-20'),
    createdBy: 'manager@incredibly.com',
    updatedAt: new Date('2026-01-14'),
    updatedBy: 'manager@incredibly.com',
    responsiveness: 88,
    nextLicenseExpiration: new Date('2026-09-30'),
    alertCount: 0,
  },
  {
    id: 'prov-018',
    firstName: 'Kevin',
    middleName: 'Paul',
    lastName: 'Moore',
    suffix: null,
    displayName: 'Dr. Kevin Moore, MD',
    credential: 'MD',
    npi: '8899001122',
    deaNumber: 'KM5566778',
    taxId: '88-9900112',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1976-09-11'),
    primarySpecialty: 'Neurology',
    secondarySpecialties: [],
    boardCertifications: ['ABN - Neurology'],
    email: 'kmoore@example.com',
    phone: '(555) 889-9001',
    fax: '(555) 889-9002',
    status: ProviderStatus.ACTIVE,
    clientIds: ['3'],
    departmentId: 'dept-016',
    businessEntityId: 'be-003',
    organizationalAffiliations: ['Three Rivers Health Network'],
    stateLicenses: [
      {
        id: 'lic-022',
        state: 'PA',
        licenseNumber: 'MD223344',
        licenseType: 'Medical',
        issueDate: new Date('2004-11-01'),
        expirationDate: new Date('2026-10-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-018',
        locationName: 'Neurology Center',
        addressLine1: '100 Technology Drive',
        addressLine2: 'Suite 400',
        city: 'Pittsburgh',
        state: 'PA',
        zip: '15219',
        phone: '(555) 889-9001',
        fax: '(555) 889-9002',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH44556',
    createdAt: new Date('2024-07-05'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-13'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 85,
    nextLicenseExpiration: new Date('2026-10-31'),
    alertCount: 0,
  },
  {
    id: 'prov-019',
    firstName: 'Sophia',
    middleName: 'Grace',
    lastName: 'Jackson',
    suffix: null,
    displayName: 'Sophia Jackson, NP-C',
    credential: 'NP-C',
    npi: '9900112233',
    deaNumber: 'SJ7788990',
    taxId: '99-0011223',
    ssn: null,
    providerType: ProviderType.NURSE_PRACTITIONER,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1987-04-16'),
    primarySpecialty: 'Pediatrics',
    secondarySpecialties: [],
    boardCertifications: ['PNCB - Pediatric Nurse Practitioner'],
    email: 'sjackson@example.com',
    phone: '(555) 990-0112',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['2'],
    departmentId: 'dept-004',
    businessEntityId: 'be-002',
    organizationalAffiliations: ['Penn Medicine Network'],
    stateLicenses: [
      {
        id: 'lic-023',
        state: 'PA',
        licenseNumber: 'RN334455',
        licenseType: 'Nursing',
        issueDate: new Date('2012-03-01'),
        expirationDate: new Date('2027-02-28'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-019',
        locationName: 'Pediatric Clinic',
        addressLine1: '321 Children Avenue',
        addressLine2: 'Floor 2',
        city: 'Philadelphia',
        state: 'PA',
        zip: '19107',
        phone: '(555) 990-0112',
        fax: '(555) 990-0113',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2024-08-10'),
    createdBy: 'manager@incredibly.com',
    updatedAt: new Date('2026-01-12'),
    updatedBy: 'manager@incredibly.com',
    responsiveness: 93,
    nextLicenseExpiration: new Date('2027-02-28'),
    alertCount: 0,
  },
  {
    id: 'prov-020',
    firstName: 'Brandon',
    middleName: 'Kyle',
    lastName: 'White',
    suffix: null,
    displayName: 'Dr. Brandon White, DO',
    credential: 'DO',
    npi: '0011223344',
    deaNumber: 'BW9900112',
    taxId: '00-1122334',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1985-02-28'),
    primarySpecialty: 'Ophthalmology',
    secondarySpecialties: [],
    boardCertifications: ['ABO - Ophthalmology'],
    email: 'bwhite@example.com',
    phone: '(555) 001-1223',
    fax: '(555) 001-1224',
    status: ProviderStatus.ACTIVE,
    clientIds: ['4'],
    departmentId: 'dept-017',
    businessEntityId: 'be-004',
    organizationalAffiliations: ['Lehigh Valley Medical Network'],
    stateLicenses: [
      {
        id: 'lic-024',
        state: 'PA',
        licenseNumber: 'DO445566',
        licenseType: 'Medical',
        issueDate: new Date('2014-07-01'),
        expirationDate: new Date('2026-06-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-020',
        locationName: 'Eye Care Center',
        addressLine1: '1247 South Cedar Crest Blvd',
        addressLine2: 'Suite 100',
        city: 'Scranton',
        state: 'PA',
        zip: '18103',
        phone: '(555) 001-1223',
        fax: '(555) 001-1224',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH66778',
    createdAt: new Date('2024-09-15'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-11'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 89,
    nextLicenseExpiration: new Date('2026-06-30'),
    alertCount: 0,
  },
  // Additional 5 more providers
  {
    id: 'prov-021',
    firstName: 'Nicole',
    middleName: 'Marie',
    lastName: 'Martin',
    suffix: null,
    displayName: 'Dr. Nicole Martin, MD',
    credential: 'MD',
    npi: '1123344556',
    deaNumber: 'NM2233445',
    taxId: '11-2334455',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1983-11-09'),
    primarySpecialty: 'Endocrinology',
    secondarySpecialties: ['Diabetes Management'],
    boardCertifications: ['ABIM - Endocrinology'],
    email: 'nmartin@example.com',
    phone: '(555) 112-3344',
    fax: '(555) 112-3345',
    status: ProviderStatus.ACTIVE,
    clientIds: ['1'],
    departmentId: 'dept-018',
    businessEntityId: 'be-001',
    organizationalAffiliations: ['Keystone Health Partners'],
    stateLicenses: [
      {
        id: 'lic-025',
        state: 'PA',
        licenseNumber: 'MD556677',
        licenseType: 'Medical',
        issueDate: new Date('2011-05-01'),
        expirationDate: new Date('2026-04-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-021',
        locationName: 'Endocrinology Associates',
        addressLine1: '123 Medical Center Drive',
        addressLine2: 'Building C',
        city: 'West Reading',
        state: 'PA',
        zip: '19601',
        phone: '(555) 112-3344',
        fax: '(555) 112-3345',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH88990',
    createdAt: new Date('2024-10-20'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-10'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 91,
    nextLicenseExpiration: new Date('2026-04-30'),
    alertCount: 0,
  },
  {
    id: 'prov-022',
    firstName: 'Gregory',
    middleName: 'Thomas',
    lastName: 'Clark',
    suffix: null,
    displayName: 'Dr. Gregory Clark, MD',
    credential: 'MD',
    npi: '2234455667',
    deaNumber: 'GC4455667',
    taxId: '22-3445566',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1979-06-14'),
    primarySpecialty: 'Gastroenterology',
    secondarySpecialties: [],
    boardCertifications: ['ABIM - Gastroenterology'],
    email: 'gclark@example.com',
    phone: '(555) 223-4455',
    fax: '(555) 223-4456',
    status: ProviderStatus.ACTIVE,
    clientIds: ['2', '3'],
    departmentId: 'dept-019',
    businessEntityId: 'be-002',
    organizationalAffiliations: ['Penn Medicine Network', 'Three Rivers Health Network'],
    stateLicenses: [
      {
        id: 'lic-026',
        state: 'PA',
        licenseNumber: 'MD667788',
        licenseType: 'Medical',
        issueDate: new Date('2006-09-01'),
        expirationDate: new Date('2026-08-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-022',
        locationName: 'Digestive Health Center',
        addressLine1: '3400 Civic Center Blvd',
        addressLine2: 'Pavilion 6',
        city: 'Philadelphia',
        state: 'PA',
        zip: '19104',
        phone: '(555) 223-4455',
        fax: '(555) 223-4456',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH00112',
    createdAt: new Date('2024-11-05'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-09'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 87,
    nextLicenseExpiration: new Date('2026-08-31'),
    alertCount: 0,
  },
  {
    id: 'prov-023',
    firstName: 'Lauren',
    middleName: 'Ashley',
    lastName: 'Robinson',
    suffix: null,
    displayName: 'Lauren Robinson, NP-C',
    credential: 'NP-C',
    npi: '3345566778',
    deaNumber: 'LR6677889',
    taxId: '33-4556677',
    ssn: null,
    providerType: ProviderType.NURSE_PRACTITIONER,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1990-08-25'),
    primarySpecialty: 'Cardiology',
    secondarySpecialties: [],
    boardCertifications: ['ANCC - Acute Care Nurse Practitioner'],
    email: 'lrobinson@example.com',
    phone: '(555) 334-5566',
    fax: null,
    status: ProviderStatus.ACTIVE,
    clientIds: ['7'],
    departmentId: 'dept-002',
    businessEntityId: 'be-007',
    organizationalAffiliations: ['Allegheny Cardiology Associates'],
    stateLicenses: [
      {
        id: 'lic-027',
        state: 'PA',
        licenseNumber: 'RN778899',
        licenseType: 'Nursing',
        issueDate: new Date('2015-11-01'),
        expirationDate: new Date('2027-10-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-023',
        locationName: 'Cardiology Associates',
        addressLine1: '200 Delafield Road',
        addressLine2: null,
        city: 'Pittsburgh',
        state: 'PA',
        zip: '15215',
        phone: '(555) 334-5566',
        fax: '(555) 334-5567',
        isPrimary: true,
      },
    ],
    caqhId: null,
    createdAt: new Date('2024-12-01'),
    createdBy: 'manager@incredibly.com',
    updatedAt: new Date('2026-01-08'),
    updatedBy: 'manager@incredibly.com',
    responsiveness: 94,
    nextLicenseExpiration: new Date('2027-10-31'),
    alertCount: 0,
  },
  {
    id: 'prov-024',
    firstName: 'Samuel',
    middleName: 'David',
    lastName: 'Lewis',
    suffix: null,
    displayName: 'Dr. Samuel Lewis, MD',
    credential: 'MD',
    npi: '4456677889',
    deaNumber: 'SL8899001',
    taxId: '44-5667788',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.MALE,
    dateOfBirth: new Date('1981-03-07'),
    primarySpecialty: 'Urology',
    secondarySpecialties: [],
    boardCertifications: ['ABU - Urology'],
    email: 'slewis@example.com',
    phone: '(555) 445-6677',
    fax: '(555) 445-6678',
    status: ProviderStatus.PENDING,
    clientIds: ['3'],
    departmentId: 'dept-020',
    businessEntityId: 'be-003',
    organizationalAffiliations: ['Three Rivers Health Network'],
    stateLicenses: [
      {
        id: 'lic-028',
        state: 'PA',
        licenseNumber: 'MD889900',
        licenseType: 'Medical',
        issueDate: new Date('2010-12-01'),
        expirationDate: new Date('2026-11-30'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-024',
        locationName: 'Urology Center',
        addressLine1: '100 Technology Drive',
        addressLine2: 'Suite 500',
        city: 'Pittsburgh',
        state: 'PA',
        zip: '15219',
        phone: '(555) 445-6677',
        fax: '(555) 445-6678',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH22334',
    createdAt: new Date('2025-01-10'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-07'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 80,
    nextLicenseExpiration: new Date('2026-11-30'),
    alertCount: 1,
  },
  {
    id: 'prov-025',
    firstName: 'Angela',
    middleName: 'Lynn',
    lastName: 'Hall',
    suffix: null,
    displayName: 'Dr. Angela Hall, DO',
    credential: 'DO',
    npi: '5567788990',
    deaNumber: 'AH0011223',
    taxId: '55-6778899',
    ssn: null,
    providerType: ProviderType.PHYSICIAN,
    gender: Gender.FEMALE,
    dateOfBirth: new Date('1986-10-22'),
    primarySpecialty: 'Rheumatology',
    secondarySpecialties: [],
    boardCertifications: ['ABIM - Rheumatology'],
    email: 'ahall@example.com',
    phone: '(555) 556-7788',
    fax: '(555) 556-7789',
    status: ProviderStatus.ACTIVE,
    clientIds: ['1', '2'],
    departmentId: 'dept-021',
    businessEntityId: 'be-001',
    organizationalAffiliations: ['Keystone Health Partners', 'Penn Medicine Network'],
    stateLicenses: [
      {
        id: 'lic-029',
        state: 'PA',
        licenseNumber: 'DO990011',
        licenseType: 'Medical',
        issueDate: new Date('2015-02-01'),
        expirationDate: new Date('2027-01-31'),
        status: 'Active',
      },
    ],
    locations: [
      {
        id: 'loc-025',
        locationName: 'Rheumatology Practice',
        addressLine1: '123 Medical Center Drive',
        addressLine2: 'Building D',
        city: 'West Reading',
        state: 'PA',
        zip: '19601',
        phone: '(555) 556-7788',
        fax: '(555) 556-7789',
        isPrimary: true,
      },
    ],
    caqhId: 'CAQH44556',
    createdAt: new Date('2025-02-01'),
    createdBy: 'admin@incredibly.com',
    updatedAt: new Date('2026-01-06'),
    updatedBy: 'admin@incredibly.com',
    responsiveness: 86,
    nextLicenseExpiration: new Date('2027-01-31'),
    alertCount: 0,
  },
];

/**
 * Mock documents for providers
 */
export const mockProviderDocuments: Record<string, ProviderDocument[]> = {
  'prov-001': [
    {
      id: 'doc-001',
      providerId: 'prov-001',
      name: 'PA_Medical_License.pdf',
      type: 'License',
      uploadedAt: new Date('2023-01-20'),
      uploadedBy: 'admin@incredibly.com',
      size: 1024000,
      url: '#',
      fileType: 'pdf',
    },
    {
      id: 'doc-002',
      providerId: 'prov-001',
      name: 'DEA_Certificate.pdf',
      type: 'DEA',
      uploadedAt: new Date('2023-01-21'),
      uploadedBy: 'admin@incredibly.com',
      size: 512000,
      url: '#',
      fileType: 'pdf',
    },
    {
      id: 'doc-003',
      providerId: 'prov-001',
      name: 'CV_Resume.docx',
      type: 'CV/Resume',
      uploadedAt: new Date('2023-01-22'),
      uploadedBy: 'jchen@example.com',
      size: 2048000,
      url: '#',
      fileType: 'docx',
    },
  ],
};

/**
 * Mock activity log for providers
 */
export const mockProviderActivity: Record<string, ProviderActivity[]> = {
  'prov-001': [
    {
      id: 'act-001',
      timestamp: new Date('2026-01-20T10:30:00'),
      action: 'Provider created',
      performedBy: 'Admin User',
      details: 'New provider record created',
    },
    {
      id: 'act-002',
      timestamp: new Date('2026-01-20T11:00:00'),
      action: 'License added',
      performedBy: 'Admin User',
      details: 'PA Medical License added',
      relatedEntityType: 'credential',
      relatedEntityId: 'lic-001',
    },
    {
      id: 'act-003',
      timestamp: new Date('2026-01-21T14:15:00'),
      action: 'Document uploaded',
      performedBy: 'Admin User',
      details: 'DEA Certificate uploaded',
      relatedEntityType: 'document',
      relatedEntityId: 'doc-002',
    },
    {
      id: 'act-004',
      timestamp: new Date('2026-01-22T09:00:00'),
      action: 'Client linked',
      performedBy: 'Coordinator',
      details: 'Linked to Keystone Health Partners',
      relatedEntityType: 'client',
      relatedEntityId: '1',
    },
  ],
};

/**
 * Helper function to get a provider by ID
 */
export function getProviderById(id: string): Provider | undefined {
  return mockProviders.find((provider) => provider.id === id);
}

/**
 * Helper function to filter and sort providers
 */
export function filterAndSortProviders(
  providers: Provider[],
  params: {
    search?: string;
    alert?: string;
    clientId?: string;
    departmentId?: string;
    businessEntityId?: string;
    status?: ProviderStatus;
    sortBy?: string;
    sortOrder?: 'asc' | 'desc';
  }
): Provider[] {
  let filtered = [...providers];

  // Apply search filter (name or NPI)
  if (params.search) {
    const searchLower = params.search.toLowerCase();
    filtered = filtered.filter(
      (provider) =>
        provider.displayName.toLowerCase().includes(searchLower) ||
        provider.npi.includes(searchLower) ||
        provider.firstName.toLowerCase().includes(searchLower) ||
        provider.lastName.toLowerCase().includes(searchLower)
    );
  }

  // Apply client filter
  if (params.clientId) {
    filtered = filtered.filter((provider) =>
      provider.clientIds.includes(params.clientId!)
    );
  }

  // Apply department filter
  if (params.departmentId) {
    filtered = filtered.filter(
      (provider) => provider.departmentId === params.departmentId
    );
  }

  // Apply business entity filter
  if (params.businessEntityId) {
    filtered = filtered.filter(
      (provider) => provider.businessEntityId === params.businessEntityId
    );
  }

  // Apply status filter
  if (params.status) {
    filtered = filtered.filter((provider) => provider.status === params.status);
  }

  // Apply alert filter
  if (params.alert) {
    if (params.alert === 'expiring') {
      filtered = filtered.filter((provider) => {
        if (!provider.nextLicenseExpiration) return false;
        const daysUntilExpiration = Math.floor(
          (provider.nextLicenseExpiration.getTime() - Date.now()) / (1000 * 60 * 60 * 24)
        );
        return daysUntilExpiration < 90;
      });
    }
  }

  // Apply sorting
  if (params.sortBy) {
    filtered.sort((a, b) => {
      let aValue: string | number = (a[params.sortBy as keyof Provider] as string | number) ?? '';
      let bValue: string | number = (b[params.sortBy as keyof Provider] as string | number) ?? '';

      // Handle nested properties
      if (params.sortBy === 'specialty') {
        aValue = a.primarySpecialty;
        bValue = b.primarySpecialty;
      } else if (params.sortBy === 'licenseExpiration') {
        aValue = a.nextLicenseExpiration?.getTime() || 0;
        bValue = b.nextLicenseExpiration?.getTime() || 0;
      }

      if (typeof aValue === 'string' && typeof bValue === 'string') {
        aValue = aValue.toLowerCase();
        bValue = bValue.toLowerCase();
      }

      if ((aValue ?? '') < (bValue ?? '')) return params.sortOrder === 'asc' ? -1 : 1;
      if ((aValue ?? '') > (bValue ?? '')) return params.sortOrder === 'asc' ? 1 : -1;
      return 0;
    });
  }

  return filtered;
}

/**
 * Helper function to paginate providers
 */
export function paginateProviders(
  providers: Provider[],
  page: number = 1,
  limit: number = 25
) {
  const start = (page - 1) * limit;
  const end = start + limit;
  const paginatedProviders = providers.slice(start, end);
  const totalPages = Math.ceil(providers.length / limit);

  return {
    providers: paginatedProviders,
    pagination: {
      page,
      limit,
      total: providers.length,
      totalPages,
      hasMore: page < totalPages,
    },
  };
}
