export type RoleCode =
  | "ROLE_SUPER_ADMIN"
  | "ROLE_MANAGER"
  | "ROLE_TEAM_LEAD"
  | "ROLE_ANALYST"
  | "ROLE_VERIFICATION"
  | "ROLE_QC_ANALYST"
  | "ROLE_SCHEMA_ANALYST"
  | "ROLE_CLIENT_ADMIN"
  | "ROLE_MSO_DIRECTOR"
  | "ROLE_CLIENT_USER"
  | "ROLE_ACCOUNTING"
  | "ROLE_RECRUITER"
  | "ROLE_PROVIDER";